### ISSUE TITLE
Paintbrushes do not show up in the creative inventory 

### ISSUE THREAD

**Issue by thelegitdolt** [KekeCreations/Arts-and-Crafts#1]
<img width="844" alt="Screenshot 2024-06-11 at 3 09 01 PM" src="https://github.com/KekeCreations/Arts-and-Crafts/assets/50085439/e3f9bdde-039a-47fe-b372-e009add9373f">

**Comment by KekeCreations** [comment]
I haven't had this issue with any mods I've played, can you send mod list and logs?

**Comment by thelegitdolt** [comment]
Oh yeah absolutely

https://gist.github.com/thelegitdolt/287256ecaea8ce4776f8b53ffaabcd39 < lates.log
https://gist.github.com/thelegitdolt/cabefb26b8bdcb3041c8c89af25d5868 < modlist

**Comment by KekeCreations** [comment]
You appear to have a mod that changes the creative category by looking at the logs, can you try disabling it and see if the problem continues? This does not happen normally and is a mod conflict

**Comment by KekeCreations** [comment]
Fixed in V1.1.0
