### ISSUE TITLE
Missing translation key for Bleached Chalk Dust block

### ISSUE THREAD

**Issue by Clarthen** [KekeCreations/Arts-and-Crafts#10]
`block.arts_and_crafts.bleached_chalk_dust` translation key is missing in `en_us.json`.

**Comment by KekeCreations** [comment]
Does anything use this translation? I mean in Minecraft with just the base mod, theres no way to actually see the translation because the block doesn't have a block item.

**Comment by KekeCreations** [comment]
nvm Jade does, will fix next update!

**Comment by KekeCreations** [comment]
Fixed in V1.1.4
