### ISSUE TITLE
Memory overload crash

### ISSUE THREAD

**Issue by dragonfire0612** [KekeCreations/Arts-and-Crafts#14]
Upon updating to Arts & Crafts version 1.1.4 for NeoForge, the mod causes a RAM overload when trying to access the inventory while in creative mode.

**Comment by dragonfire0612** [comment]
![Screenshot 2024-07-08 181037](https://github.com/KekeCreations/Arts-and-Crafts/assets/40594943/bd4384c4-135c-402c-af41-b08465afbc72)

**Comment by KekeCreations** [comment]
Fixed in V1.1.4-bugfix
