### ISSUE TITLE
Copying a chalk dust pattern doesnt work while flying

### ISSUE THREAD

**Issue by Hecco56** [KekeCreations/Arts-and-Crafts#19]
As it says in the title, crouching/moving downwards while flying doesn't let you copy chalk dust patterns, instead it cycles to the next one as if you weren't crouching. This is inconsistent with other interactions that happen while crouching, such as placing blocks on chests.

**Comment by KekeCreations** [comment]
Fixed in V2.0.0, thank you for reporting!

**Comment by KekeCreations** [comment]
Moved this fix to V1.1.9
