### ISSUE TITLE
Bleached Chalk drawings cause crash when using Jade (Neoforge 1.20.1)

### ISSUE THREAD

**Issue by Hahahavana** [KekeCreations/Arts-and-Crafts#2]
What the title says. The game does not crash when using One Probe, nor do other colors of chalk cause issues, but bleached chalk drawings specifically don't appear at all where you'd expect when you hover over then. It simply spams the log with "[Render thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "net.minecraft.world.item.DyeColor.m_41060_()" because "this.dyeColor" is null".

Other bleached items do not have this issue.

**Comment by KekeCreations** [comment]
Fixed in V1.0.2. Thank you for reporting this issue and helping the mod work better for everyone else!
