### ISSUE TITLE
[Suggestion] Feature generation should take use of biome tags

### ISSUE THREAD

**Issue by Yirmiri** [KekeCreations/Arts-and-Crafts#22]
Features such as chalk and gypsum blobs should take use of biome tags like `is_desert` or `is_mountain` as it is extremely hard to find these features in worlds with modded biomes

**Comment by KekeCreations** [comment]
biome tags like `is_desert` does not exist and chalk feature is already using `is_mountain`

In V2.0.0
- I made chalk blobs generate more often in mountains
- I made chalk now replace all blocks in the `#minecraft:base_stone_overworld` tag
- I made gypsum generate in biomes with a Desert Temple
This update won't be out for a bit but hopefully these changes will help out!

**Comment by KekeCreations** [comment]
Moved the above changes to V1.1.9
