### ISSUE TITLE
Texture support for Gilded Sherds

### ISSUE THREAD

**Issue by Jous4n** [KekeCreations/Arts-and-Crafts#25]
Not exactly an issue, but would be cool to have dyed gilded decorated pots (:
https://modrinth.com/mod/gilded-sherds

I'm enjoying the Arts & Crafts mod so far! The brushes are so smooth and dynamic to use! :D
![image](https://github.com/user-attachments/assets/9fb83af9-7be3-4077-a50b-ae1faf6e1291)

**Comment by KekeCreations** [comment]
Hey, I actually added compat in the Arts & Crafts Compat mod!

**Comment by KekeCreations** [comment]
You can download it here : https://modrinth.com/mod/artsandcrafts-compatibility

**Comment by KekeCreations** [comment]
I'm glad you are enjoying the mod, I will leave this open just in case you require anything else, please do close it when you are ready!

**Comment by Jous4n** [comment]
Oh awesome! Thanks! By the way, is there any compatibility for Item Pots (datapack)?

**Comment by KekeCreations** [comment]
Do you have a link to the datapack? I can then look into compat for it!

**Comment by Jous4n** [comment]
Yup! Here it is: https://modrinth.com/datapack/item-pots
It is deprecated, but only because this is already a feature in 1.20.4.
Though, for my modpack (1.20.1) it is still pretty useful.

Sorry for late reply!
