### ISSUE TITLE
Dedicated server crash on startup (A&C 1.3.0 on 1.21.1 NeoForge)

### ISSUE THREAD

**Issue by asrieldashie** [KekeCreations/Arts-and-Crafts#31]
Tested with only A&C itself
NeoForge version 21.1.80

[latest.log](https://github.com/user-attachments/files/17882638/latest.log)
[crash-2024-11-24_05.32.47-fml.txt](https://github.com/user-attachments/files/17882639/crash-2024-11-24_05.32.47-fml.txt)

**Comment by KekeCreations** [comment]
Thank you, working on fixing this rn

**Comment by KekeCreations** [comment]
Fixed in V1.3.1 (version is out now!)
