### ISSUE TITLE
Changing chalk pattern crashes server

### ISSUE THREAD

**Issue by Deloptin** [KekeCreations/Arts-and-Crafts#32]
https://mclo.gs/49owa8m (Link defunct 90 days after last view)

Running a dedicated server with friends, right-clicking a chalk pattern immediately causes the server to stop. This didn't happen when we were hosting on our own computers using e4mc, so the issue probably has something to do with it being on a server. No clue how to decipher the crash log, so any help would be appreciated 👍

**Comment by KekeCreations** [comment]
com.illusivesoulworks.diet.platform.services.FabricRegistryService.getPickStack(FabricRegistryService.java:124)

It appears to be a mod compat issue with this here ^

I'm not familiar with illusivesoulwork mods, which ones do you have installed so I can look into it?

**Comment by Deloptin** [comment]
> I'm not familiar with illusivesoulwork mods, which ones do you have installed so I can look into it?

Polymorph, Comforts, and [Diet](https://github.com/illusivesoulworks/diet), which seems to be the one named in the log. Thanks for checking the logs, I completely missed that bit.

**Comment by KekeCreations** [comment]
Hi, thank you, I fixed this in V1.3.2.
Thank you for playing the mod!
