### ISSUE TITLE
Dyed flower pots become normal after taking the flower out

### ISSUE THREAD

**Issue by SKYY999** [KekeCreations/Arts-and-Crafts#7]
I've found this issue out when me and my freind played on our server. 

We just got some clay and we made dyed flower pots from them. A red one in my room in our base, but passing next to it i noticed it wasn't red anymore (i changed the plant a couple times.) I've fully noticed that taking the plant out of the pot is the thing making the change, as later i saw a blue flower pot becoming normal, and a pink one after i took the flower out. I don't know if this is because the fabric API version which is not the newest, but this is an issue nonetheless.

 Tested on fabric API 0.100.3+1.21
Mod version: Arts & Crafts Fabric-1.21-V1.1.2

**Comment by KekeCreations** [comment]
Fixed in V1.1.3, thank you for reporting!
