### ISSUE TITLE
Mod loading error for NeoForge 21.0.40

### ISSUE THREAD

**Issue by CsillaAria** [KekeCreations/Arts-and-Crafts#8]
I had to update the NeoForge version to 21.0.40 for another mod that updated, and Arts and Crafts 1.21-1.1.2 fails to load. 

Here is the crash report: https://bytebin.lucko.me/JtQPGH33p1

**Comment by KekeCreations** [comment]
According to that crash report you don't even have Arts & Crafts installed
Can you make sure the Arts & Crafts jar is installed and maybe downgrade your neoforge version to 21.0.1 as I know that works

**Comment by KekeCreations** [comment]
Okay I have found a problem, if you downgrade to 21.0.1 it works, I will figure out how to fix this on newer NeoForge versions, seems like they changed something!

**Comment by CsillaAria** [comment]
This is actually the second mod I've had a loading error with with after updating NeoForge versions. The first one was Curios API Continuation. I worry this is going to be a recurring issue on NeoForge's end.

**Comment by KekeCreations** [comment]
Its just because Neoforge decided to change some stuff, anyway I have fixed this issue in V1.1.3 and that is out now!
