### ISSUE TITLE
Colored Flower Pots cannot hold modded plants

### ISSUE THREAD

**Issue by FumpleWumper** [KekeCreations/Arts-and-Crafts#9]
I'm playing on Fabric 0.15.11, Minecraft 1.20.1, and Arts and Crafts 1.1.3.

I've noticed that the colored flower pots can't actually hold modded plants that regular pots can otherwise, such as plants from Regions Unexplored, could there be a way to fix this somehow as well as make sure it could be compatible with any pottable plant from any mod?

Thanks and amazing work on the mod!

**Comment by KekeCreations** [comment]
This is a compat issue, and I am working on compat with mods but for compat related features you have to download Arts & Crafts Compatibility on CF or Modrinth with Arts & Crafts. I will add Regions Unexplored to the TODO list, please feel free to suggest more compat stuff!

**Comment by Nol-IsntUse** [comment]
can compat for ecologics be added

**Comment by KekeCreations** [comment]
Done compat for ecologics, will be avaliable next update, unfortantly I couldn't do compat for Regions Unexplored because of I ran into issues with the current code base, I heard they are switching to Multiloader and I will be able to do compat after they have done that!  Thank you!
